### ISSUE TITLE
russian translated text in button on https://wallet.testnet.near.org/ overflows the parent

### ISSUE THREAD

**Issue by nazariyv** [near-examples/erc20-to-nep21#4]
this is unrelated to this example, so feel free to close and point me to the right repo

<img width="132" alt="CleanShot 2020-09-30 at 14 04 34@2x" src="https://user-images.githubusercontent.com/13678461/94688838-09069900-0326-11eb-81ea-ec20f5ad6cd0.png">

**Comment by chadoh** [comment]
Thanks for the report, @nazariyv! You can post it here: https://github.com/near/near-wallet
